### ISSUE TITLE
Use more boost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apoch/epoch-language#144]
```
Currently we use a lot of platform specific features, such as windows critical 
sections, CreateThread, FindFirst/NextFiles.

A lot of this can be replaced with more platform agnostic code through the use 
of boost. Particular libraries we should evaluate and extend usage of include:

boost::filesystem
    - supports directory iteration, so we can eliminate such code.
boost::thread
    - has mutex and threads, what more do you want? :P
```

Original issue reported on code.google.com by `ryoohki@gmail.com` on 20 Feb 2012 at 1:20

**Comment by apoch** [comment]
Most of this is now doable with the C++11 or C++14 standard libraries. Moreover we now have a much thinner C++ layer in general and almost zero runtime need for Windows (aside from the obvious lack of an ELF or comparable binary emitter). I'm going to close this out to clean up the issue tracker.
