### ISSUE TITLE
buffer type is confusing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apoch/epoch-language#152]
```
Change buffers from using wchar_t sizes to using byte sizes. Buffers of raw 
bytes just make more sense.
```

Original issue reported on code.google.com by `don.ap...@gmail.com` on 19 Nov 2012 at 5:36

**Comment by apoch** [comment]
Documentation is all subject to rewrite at this point so I'm closing this out to clean up the issue tracker.
