### ISSUE TITLE
Compiler: bulk test harness

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apoch/epoch-language#167]
```
Reimplement features to allow for all compiler unit tests to be run in bulk, 
and aggregated stats reported at the end of the run.
```

Original issue reported on code.google.com by `don.ap...@gmail.com` on 5 Sep 2014 at 5:29

**Comment by apoch** [comment]
The code in `EpochTests\Projects\TestSuite` now has a stats report. Broken tests will (usually) cause the entire suite to fail, either to compile or to execute without crashing, but that's not a terrible tradeoff. Fuzz testing and diagnostic testing should be considered separate test suites for the future.
