### ISSUE TITLE
Reimplement generic array support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apoch/epoch-language#72]
```
Decide on a syntax and general mechanism of operation for supporting general 
data arrays; utilize this functionality for storing arbitrary primitives and 
POD structures.
```

Original issue reported on code.google.com by `don.ap...@gmail.com` on 12 Oct 2010 at 5:53

**Comment by apoch** [comment]
The last several commits have introduced array syntax, array initialization, and array reads. Assignments are still pending as well as passing array slots by reference and other semantic features.

**Comment by apoch** [comment]
Assignments into arrays are now baseline functional. There will be a lot of cleanup needed to generalize the parsing and IR for assignments now that arrays are present in the language. Separate issues/tracking bugs can be filed as needed, for the purposes of this (ancient!) issue I'm closing it out.
